<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>clp</string>
	</array>
	<key>name</key>
	<string>CLIPS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>;</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.clips</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comments line</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.clips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(type|default|allowed-values|slot|not|or|and|assert|retract|gensym|printout|declare|salience|modify|export)\b</string>
			<key>name</key>
			<string>keyword.control.clips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>RHD</string>
			<key>match</key>
			<string>=&gt;</string>
			<key>name</key>
			<string>constant.language.clips</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.clips</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Functions</string>
			<key>match</key>
			<string>(\?)([a-zA-Z0-9_\-]*)</string>
			<key>name</key>
			<string>meta.function.clips</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.clips</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.clips</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Definitions</string>
			<key>match</key>
			<string>(^.*(defrule|deffacts|defmodule|deftemplate)[ \t]+)([a-zA-Z0-9_\-]+)</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constant A</string>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.other.color.rgb-value.css</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constant B</string>
			<key>match</key>
			<string>(&lt;-|~|%)</string>
			<key>name</key>
			<string>constant.language.clips</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constant C</string>
			<key>match</key>
			<string>(|=|&gt;|\\-|\\+|\\*|\\/|~|%|neq|eq)</string>
			<key>name</key>
			<string>constant.language.clips</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.clips</string>
	<key>uuid</key>
	<string>1b2ecbe9-9ccb-401d-8707-9440305081df</string>
</dict>
</plist>
